// import { StylesProvider } from './styles-provider'
import { TamaguiStyles } from './TamaguiStyles' // Создадим его сейчас
import { NextTamaguiProvider } from './NextTamaguiProvider'
import './globals.css'

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode | React.JSX.Element
}) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <head>
        <TamaguiStyles />
      </head>
      <body>
        <NextTamaguiProvider>{children}</NextTamaguiProvider>
        {/* <StylesProvider>{children}</StylesProvider> */}
      </body>
    </html>
  )
}
